name: 'Polyrific.Catapult.Plugins.MSBuild'
type: 'BuildProvider'
author: 'Polyrific'
version: '1.0'
additional-configs:
  - name: SlnLocation
    label: Solution Location
    type: string
    is-required: false
    is-secret: false
  - name: Configuration
    label: Configuration
    type: string
    is-required: false
    is-secret: false